services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: moon_backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - moon_net

  tg-bot:
    build:
      context: ./tg-bot
      dockerfile: Dockerfile
    container_name: moon_tgbot
    env_file:
      - ./.env
    restart: always
    depends_on:
      - backend
      - db
      - redis
    networks:
      - moon_net

  db:
    image: mysql:8.0
    container_name: moon_db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - moon_db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - moon_net

  redis:
    image: redis:7-alpine
    container_name: moon_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - moon_net

  images:
    image: nginx:alpine
    container_name: moon_images
    volumes:
      - ./images:/usr/share/nginx/html:ro
    ports:
      - "${IMAGES_PORT:-5001}:80"
    restart: unless-stopped
    networks:
      - moon_net

volumes:
  moon_db_data:

networks:
  moon_net:
    driver: bridge