/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GiftMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "burnPresent"
      | "burnRefundPercent"
      | "buyPresent"
      | "delistPresent"
      | "getListing"
      | "getPresentOwner"
      | "listPresent"
      | "listings"
      | "marketplaceFeePercent"
      | "owner"
      | "platformWallet"
      | "presentOwner"
      | "purchasePresent"
      | "purchasePrice"
      | "setFees"
      | "token"
      | "upgradeFeePercent"
      | "upgradePresent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PresentBurned"
      | "PresentDelisted"
      | "PresentListed"
      | "PresentPurchased"
      | "PresentSold"
      | "PresentUpgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "burnPresent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnRefundPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyPresent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "delistPresent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPresentOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listPresent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplaceFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presentOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchasePresent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchasePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradePresent",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "burnPresent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnRefundPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyPresent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "delistPresent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPresentOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listPresent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketplaceFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presentOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchasePresent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchasePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradePresent",
    data: BytesLike
  ): Result;
}

export namespace PresentBurnedEvent {
  export type InputTuple = [
    presentId: BigNumberish,
    owner: AddressLike,
    refund: BigNumberish
  ];
  export type OutputTuple = [presentId: bigint, owner: string, refund: bigint];
  export interface OutputObject {
    presentId: bigint;
    owner: string;
    refund: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PresentDelistedEvent {
  export type InputTuple = [presentId: BigNumberish, seller: AddressLike];
  export type OutputTuple = [presentId: bigint, seller: string];
  export interface OutputObject {
    presentId: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PresentListedEvent {
  export type InputTuple = [
    presentId: BigNumberish,
    seller: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [presentId: bigint, seller: string, price: bigint];
  export interface OutputObject {
    presentId: bigint;
    seller: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PresentPurchasedEvent {
  export type InputTuple = [
    presentId: BigNumberish,
    buyer: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [presentId: bigint, buyer: string, price: bigint];
  export interface OutputObject {
    presentId: bigint;
    buyer: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PresentSoldEvent {
  export type InputTuple = [
    presentId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    price: BigNumberish,
    platformFee: BigNumberish,
    sellerReceived: BigNumberish
  ];
  export type OutputTuple = [
    presentId: bigint,
    buyer: string,
    seller: string,
    price: bigint,
    platformFee: bigint,
    sellerReceived: bigint
  ];
  export interface OutputObject {
    presentId: bigint;
    buyer: string;
    seller: string;
    price: bigint;
    platformFee: bigint;
    sellerReceived: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PresentUpgradedEvent {
  export type InputTuple = [
    presentId: BigNumberish,
    owner: AddressLike,
    fee: BigNumberish
  ];
  export type OutputTuple = [presentId: bigint, owner: string, fee: bigint];
  export interface OutputObject {
    presentId: bigint;
    owner: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GiftMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): GiftMarketplace;
  waitForDeployment(): Promise<this>;

  interface: GiftMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  burnPresent: TypedContractMethod<
    [presentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  burnRefundPercent: TypedContractMethod<[], [bigint], "view">;

  buyPresent: TypedContractMethod<
    [presentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  delistPresent: TypedContractMethod<
    [presentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getListing: TypedContractMethod<
    [presentId: BigNumberish],
    [
      [string, bigint, boolean] & {
        seller: string;
        price: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getPresentOwner: TypedContractMethod<
    [presentId: BigNumberish],
    [string],
    "view"
  >;

  listPresent: TypedContractMethod<
    [presentId: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean] & {
        presentId: bigint;
        seller: string;
        price: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  marketplaceFeePercent: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformWallet: TypedContractMethod<[], [string], "view">;

  presentOwner: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  purchasePresent: TypedContractMethod<
    [presentId: BigNumberish, basePrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  purchasePrice: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  setFees: TypedContractMethod<
    [
      _marketplaceFee: BigNumberish,
      _upgradeFee: BigNumberish,
      _burnRefund: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  upgradeFeePercent: TypedContractMethod<[], [bigint], "view">;

  upgradePresent: TypedContractMethod<
    [presentId: BigNumberish, upgradeCost: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "burnPresent"
  ): TypedContractMethod<[presentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "burnRefundPercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyPresent"
  ): TypedContractMethod<[presentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "delistPresent"
  ): TypedContractMethod<[presentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getListing"
  ): TypedContractMethod<
    [presentId: BigNumberish],
    [
      [string, bigint, boolean] & {
        seller: string;
        price: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPresentOwner"
  ): TypedContractMethod<[presentId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "listPresent"
  ): TypedContractMethod<
    [presentId: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean] & {
        presentId: bigint;
        seller: string;
        price: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketplaceFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "presentOwner"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "purchasePresent"
  ): TypedContractMethod<
    [presentId: BigNumberish, basePrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "purchasePrice"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFees"
  ): TypedContractMethod<
    [
      _marketplaceFee: BigNumberish,
      _upgradeFee: BigNumberish,
      _burnRefund: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "upgradeFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "upgradePresent"
  ): TypedContractMethod<
    [presentId: BigNumberish, upgradeCost: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PresentBurned"
  ): TypedContractEvent<
    PresentBurnedEvent.InputTuple,
    PresentBurnedEvent.OutputTuple,
    PresentBurnedEvent.OutputObject
  >;
  getEvent(
    key: "PresentDelisted"
  ): TypedContractEvent<
    PresentDelistedEvent.InputTuple,
    PresentDelistedEvent.OutputTuple,
    PresentDelistedEvent.OutputObject
  >;
  getEvent(
    key: "PresentListed"
  ): TypedContractEvent<
    PresentListedEvent.InputTuple,
    PresentListedEvent.OutputTuple,
    PresentListedEvent.OutputObject
  >;
  getEvent(
    key: "PresentPurchased"
  ): TypedContractEvent<
    PresentPurchasedEvent.InputTuple,
    PresentPurchasedEvent.OutputTuple,
    PresentPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "PresentSold"
  ): TypedContractEvent<
    PresentSoldEvent.InputTuple,
    PresentSoldEvent.OutputTuple,
    PresentSoldEvent.OutputObject
  >;
  getEvent(
    key: "PresentUpgraded"
  ): TypedContractEvent<
    PresentUpgradedEvent.InputTuple,
    PresentUpgradedEvent.OutputTuple,
    PresentUpgradedEvent.OutputObject
  >;

  filters: {
    "PresentBurned(uint256,address,uint256)": TypedContractEvent<
      PresentBurnedEvent.InputTuple,
      PresentBurnedEvent.OutputTuple,
      PresentBurnedEvent.OutputObject
    >;
    PresentBurned: TypedContractEvent<
      PresentBurnedEvent.InputTuple,
      PresentBurnedEvent.OutputTuple,
      PresentBurnedEvent.OutputObject
    >;

    "PresentDelisted(uint256,address)": TypedContractEvent<
      PresentDelistedEvent.InputTuple,
      PresentDelistedEvent.OutputTuple,
      PresentDelistedEvent.OutputObject
    >;
    PresentDelisted: TypedContractEvent<
      PresentDelistedEvent.InputTuple,
      PresentDelistedEvent.OutputTuple,
      PresentDelistedEvent.OutputObject
    >;

    "PresentListed(uint256,address,uint256)": TypedContractEvent<
      PresentListedEvent.InputTuple,
      PresentListedEvent.OutputTuple,
      PresentListedEvent.OutputObject
    >;
    PresentListed: TypedContractEvent<
      PresentListedEvent.InputTuple,
      PresentListedEvent.OutputTuple,
      PresentListedEvent.OutputObject
    >;

    "PresentPurchased(uint256,address,uint256)": TypedContractEvent<
      PresentPurchasedEvent.InputTuple,
      PresentPurchasedEvent.OutputTuple,
      PresentPurchasedEvent.OutputObject
    >;
    PresentPurchased: TypedContractEvent<
      PresentPurchasedEvent.InputTuple,
      PresentPurchasedEvent.OutputTuple,
      PresentPurchasedEvent.OutputObject
    >;

    "PresentSold(uint256,address,address,uint256,uint256,uint256)": TypedContractEvent<
      PresentSoldEvent.InputTuple,
      PresentSoldEvent.OutputTuple,
      PresentSoldEvent.OutputObject
    >;
    PresentSold: TypedContractEvent<
      PresentSoldEvent.InputTuple,
      PresentSoldEvent.OutputTuple,
      PresentSoldEvent.OutputObject
    >;

    "PresentUpgraded(uint256,address,uint256)": TypedContractEvent<
      PresentUpgradedEvent.InputTuple,
      PresentUpgradedEvent.OutputTuple,
      PresentUpgradedEvent.OutputObject
    >;
    PresentUpgraded: TypedContractEvent<
      PresentUpgradedEvent.InputTuple,
      PresentUpgradedEvent.OutputTuple,
      PresentUpgradedEvent.OutputObject
    >;
  };
}
